---

- name: Prepare
  hosts: molecule_hosts
  gather_facts: no
  become: yes
  tasks:
    - name: Setup LVM physical volume
      ansible.builtin.import_role:
        name: amtega.parted
      vars:
        parted_disks:
          - align: optimal
            device: /dev/sdb
            number: 1
            part_type: primary
            part_start: 0%
            part_end: 100%
            flags: [ lvm ]
            state: present
