---

- name: Verify
  hosts: molecule_hosts
  gather_facts: yes
  become: yes
  tasks:
    - name: Assert volume group was created
      assert:
        that:
          - ansible_facts.lvm.vgs.testing is defined
